#ifndef _TCBIN_POWER_IOCTL_H
#define _TCBIN_POWER_IOCTL_H

#define TCBIN_POWER_IOC_MAGIC			0xE2


#define TCBIN_POWER_GET_DRIVER_VERSION		_IOC(_IOC_READ,  TCBIN_POWER_IOC_MAGIC, 0x01, 4)
	
#define TCBIN_POWER_IOC_MAXNR			0x05

#endif /* _TCBIN_POWER_IOCTL_H */