#!/usr/bin/sh

vtNumber=1
exec <> "/dev/tty${vtNumber}" >&0 2>&1

clear
echo "Syscheck - System Maintenance and Rescue Shell"

homeDirectory="/home"
mkdir -p "${homeDirectory}"
cd "${homeDirectory}"

export SHELL="/usr/bin/sh"
export HOME="$(pwd)"
export PS1='syscheck# '

shellProfile="${HOME}/.profile"
[ ! -f "${shellProfile}" ] || . "${shellProfile}"

openvt -c "${vtNumber}" -w "${SHELL}" "${@}"
exit "${?}"
