/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zone24x7_tcbin_Braille_BrailleDisplay */

#ifndef _Included_zone24x7_tcbin_Braille_BrailleDisplay
#define _Included_zone24x7_tcbin_Braille_BrailleDisplay
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     zone24x7_tcbin_Braille_BrailleDisplay
 * Method:    nativeDisplayText
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_zone24x7_tcbin_Braille_BrailleDisplay_nativeDisplayText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zone24x7_tcbin_Braille_BrailleDisplay
 * Method:    nativeClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zone24x7_tcbin_Braille_BrailleDisplay_nativeClear
  (JNIEnv *, jobject);

/*
 * Class:     zone24x7_tcbin_Braille_BrailleDisplay
 * Method:    nativeSetDotStrength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_zone24x7_tcbin_Braille_BrailleDisplay_nativeSetDotStrength
  (JNIEnv *, jobject, jint);

/*
 * Class:     zone24x7_tcbin_Braille_BrailleDisplay
 * Method:    nativeGetRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zone24x7_tcbin_Braille_BrailleDisplay_nativeGetRows
  (JNIEnv *, jobject);

/*
 * Class:     zone24x7_tcbin_Braille_BrailleDisplay
 * Method:    nativeGetColumns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zone24x7_tcbin_Braille_BrailleDisplay_nativeGetColumns
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
