#!/system/bin/sh
DIR="/dev/block/platform/mmci-omap-hs.1/by-num"
if [ ! "$(ls -a $DIR)" ]; then
	echo "$DIR is Empty; emmc needs formating"
	for z in /dev/block/platform/mmci-omap-hs.1/mmc*; do
		echo "formatting $z"
		echo -e "o\nn\np\n1\n256\n\nw" | fdisk -u $z
		break
	done
	mkfs.ext2 -m0 -b4096 /dev/block/platform/mmci-omap-hs.1/by-num/p1
else
	echo "eMMC is already formated"
fi

